spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=BestBuilder
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bestbuilder@gmail.com
spring.mail.password=123456789
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
ip_api_bestbuilder=13.216.205.228
app.rutina.key_nombre=some_value
